// Code generated by protoc-gen-go. DO NOT EDIT.
// source: database.proto

/*
Package database is a generated protocol buffer package.

It is generated from these files:
	database.proto

It has these top-level messages:
	Titile
	Content
*/
package database

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Titile struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Titile) Reset()                    { *m = Titile{} }
func (m *Titile) String() string            { return proto.CompactTextString(m) }
func (*Titile) ProtoMessage()               {}
func (*Titile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Titile) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Titile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Content struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Category    string `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Results     string `protobuf:"bytes,4,opt,name=results" json:"results,omitempty"`
	Number      int32  `protobuf:"varint,5,opt,name=number" json:"number,omitempty"`
	Searchcount int32  `protobuf:"varint,6,opt,name=searchcount" json:"searchcount,omitempty"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Content) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Content) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Content) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Content) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

func (m *Content) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Content) GetSearchcount() int32 {
	if m != nil {
		return m.Searchcount
	}
	return 0
}

func init() {
	proto.RegisterType((*Titile)(nil), "database.titile")
	proto.RegisterType((*Content)(nil), "database.content")
}

func init() { proto.RegisterFile("database.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0xaa, 0x83, 0x30,
	0x10, 0x86, 0x89, 0x4f, 0xa3, 0x6f, 0x0a, 0x2e, 0x66, 0x51, 0x42, 0x57, 0xe2, 0xca, 0x45, 0xe9,
	0xa6, 0x37, 0xf1, 0x06, 0x31, 0x0e, 0x6d, 0x40, 0x93, 0x92, 0x8c, 0x8b, 0x1e, 0xa6, 0x77, 0x2d,
	0x04, 0xb5, 0x85, 0xee, 0xe6, 0xfb, 0x67, 0xe6, 0x83, 0x1f, 0xea, 0x51, 0xb3, 0x1e, 0x74, 0xa4,
	0xcb, 0x23, 0x78, 0xf6, 0x58, 0x6d, 0xdc, 0x9e, 0x41, 0xb2, 0x65, 0x3b, 0x11, 0xd6, 0x90, 0xd9,
	0x51, 0x89, 0x46, 0x74, 0x45, 0x9f, 0xd9, 0x11, 0x11, 0x72, 0xa7, 0x67, 0x52, 0x59, 0x23, 0xba,
	0xff, 0x3e, 0xcd, 0xed, 0x4b, 0x40, 0x69, 0xbc, 0x63, 0x72, 0xfc, 0x73, 0x7f, 0x82, 0xca, 0x68,
	0xa6, 0x9b, 0x0f, 0xcf, 0xf5, 0x67, 0xe7, 0xdd, 0xf5, 0xf7, 0x71, 0xa1, 0x82, 0x32, 0x50, 0x5c,
	0x26, 0x8e, 0x2a, 0x4f, 0xf1, 0x86, 0x78, 0x04, 0xe9, 0x96, 0x79, 0xa0, 0xa0, 0x8a, 0x64, 0x5f,
	0x09, 0x1b, 0x38, 0x44, 0xd2, 0xc1, 0xdc, 0x8d, 0x5f, 0x1c, 0x2b, 0x99, 0x96, 0xdf, 0xd1, 0x20,
	0x53, 0xbd, 0xeb, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xca, 0x9e, 0xa5, 0xf0, 0x00, 0x00, 0x00,
}
