// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	Person
	AllPerson
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AllPerson struct {
	Per []*Person `protobuf:"bytes,1,rep,name=Per" json:"Per,omitempty"`
}

func (m *AllPerson) Reset()                    { *m = AllPerson{} }
func (m *AllPerson) String() string            { return proto.CompactTextString(m) }
func (*AllPerson) ProtoMessage()               {}
func (*AllPerson) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllPerson) GetPer() []*Person {
	if m != nil {
		return m.Per
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "main.person")
	proto.RegisterType((*AllPerson)(nil), "main.all_person")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x74, 0xb8, 0xd8, 0x0a, 0x52,
	0x8b, 0x8a, 0xf3, 0xf3, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58,
	0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x1d, 0x2e, 0xae, 0xc4, 0x9c, 0x9c, 0x78, 0xa8, 0x0e, 0x39,
	0x2e, 0xe6, 0x80, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x1e, 0x3d, 0x88, 0xd9,
	0x60, 0xa9, 0x20, 0x90, 0x44, 0x12, 0x1b, 0xd8, 0x22, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc8, 0xf7, 0x55, 0x21, 0x76, 0x00, 0x00, 0x00,
}
